{
    'name': 'Sentinela CFDI Prodigia',
    'version': '18.0.1.3.10',
    'category': 'Accounting/Localizations',
    'summary': 'Emisión de CFDI 4.0 a través de Prodigia para Odoo 18 Community.',
    'depends': ['account', 'base'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'wizards/cfdi_cancel_wizard_views.xml',
        'views/res_config_settings_views.xml',
        'views/account_move_views.xml',
        'views/account_payment_register_views.xml',
        'views/stock_picking_views.xml',
        'views/res_partner_views.xml',
        'views/product_views.xml',
        'views/res_company_views.xml',
        'views/report_invoice.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
