{
    'name': 'Sentinela Syscom Integration',
    'version': '18.0.1.4.0',
    'category': 'Inventory/Syscom',
    'summary': 'Integración con API de Syscom para sincronización de catálogo, precios y stock.',
    'depends': [
        'base',
        'stock',
        'product',
        'purchase',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron_syscom.xml',
        'views/res_config_settings_views.xml',
        'views/product_views.xml',
        'views/account_move_views.xml',
        'views/purchase_order_views.xml',
        'wizard/syscom_import_wizard_views.xml',
        'wizard/syscom_cleanup_wizard_views.xml',
        'views/syscom_menus.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
