{
    'name': 'Sentinela Monitoring System',
    'version': '18.0.1.13.8',
    'category': 'Industries/Security',
    'summary': 'Sistema de monitoreo de alarmas integrado con Odoo',
    'description': """Sistema completo de monitoreo de alarmas para centrales de monitoreo.""",
    'author': 'Sentinela IT',
    'website': 'https://sentinela.mx',
    'depends': [
        'base',
        'mail',
        'sale_management',
        'account',
        'stock',
        'sentinela_subscriptions',
        'sentinela_fsm',
    ],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'data/monitoring_cron_data.xml',
        'report/alarm_event_report.xml',
        'data/ir_sequence_data.xml',
        'data/alarm_codes_data.xml',
        'wizard/alarm_handle_wizard_views.xml',
        'wizard/patrol_dispatch_wizard_views.xml',
        'wizard/alarm_bulk_close_wizard_views.xml',
        'views/monitoring_device_views.xml',
        'views/alarm_event_views.xml',
        'views/alarm_signal_views.xml',
        'views/response_team_views.xml',
        'views/alarm_code_views.xml',
        'views/alarm_code_template_views.xml',
        'views/alarm_priority_views.xml', 
        'views/res_config_settings_views.xml',
        'views/subscription_mon_final_v1.xml',
        'views/monitoring_zone_views.xml',
        'views/monitoring_menus_new.xml',
        'views/res_users_views.xml',
        'views/res_partner_views.xml',
        'views/senticar_portal_views.xml',
        'views/authorization_templates.xml',
        'views/portal_event_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sentinela_monitoring/static/src/xml/monitoring_dashboard.xml',
            'sentinela_monitoring/static/src/js/alarm_service.js',
            'sentinela_monitoring/static/src/js/monitoring_dashboard.js',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
