{
    'name': 'Sentinela Subscriptions',
    'version': '18.0.1.3.84',
    'category': 'Sales/Subscriptions',
    'depends': ['base', 'mail', 'product', 'account', 'sale', 'sentinela_digital_sign', 'sentinela_cfdi_prodigia', 'om_account_followup'],
    'data': [
        'security/subscription_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/mail_template_extension_data.xml',
        'data/mail_template_collection_data.xml',
        'views/subscription_master_view.xml',
        'views/subscription_master_view_PRO.xml',
        'views/senticar_transportista_templates.xml',
        'views/product_views.xml',
        'views/router_views.xml',
        'views/mikrotik_profile_views.xml',
        'views/contract_template_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_partner_views.xml',
        'views/res_partner_followup_es.xml',
        'views/account_move_views.xml',
        'views/menus.xml',
        'report/contract_report.xml',
        'wizard/subscription_close_wizard_views.xml',
        'wizard/subscription_extension_wizard_views.xml',
        'wizard/subscription_generate_confirm_views.xml',
        'wizard/subscription_transfer_views.xml',
        'wizard/mikrotik_traffic_views.xml',
        'wizard/subscription_selection_wizard_views.xml',
        'wizard/subscription_advance_wizard_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sentinela_subscriptions/static/src/js/traffic_graph.js',
            'sentinela_subscriptions/static/src/xml/traffic_graph.xml',
        ],
    },
    'installable': True,
    'application': True,
    'post_init_hook': 'post_init_hook',
}
