{
    'name': 'Sentinela Subscriptions',
    'version': '18.0.1.2.2',
    'category': 'Sales/Subscriptions',
    'depends': ['base', 'mail', 'product', 'account', 'sale', 'sentinela_digital_sign'],
    'data': [
        'security/subscription_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/mail_template_extension_data.xml',
        'views/subscription_master_view.xml',
        'views/subscription_master_view_PRO.xml',
        'views/product_views.xml',
        'views/router_views.xml',
        'views/mikrotik_profile_views.xml',
        'views/contract_template_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_partner_views.xml',
        'views/account_move_views.xml',
        'views/menus.xml',
        'wizard/subscription_close_wizard_views.xml',
        'wizard/subscription_extension_wizard_views.xml',
        'wizard/subscription_generate_confirm_views.xml',
        'wizard/subscription_transfer_views.xml',
        'wizard/mikrotik_traffic_views.xml',
        'wizard/subscription_selection_wizard_views.xml',
    ],
    'installable': True,
    'application': True,
    'post_init_hook': 'post_init_hook',
}
